### ISSUE TITLE
Variable in payload

### ISSUE THREAD

**Issue by vjay21** [lima1909/resty.nvim#7]
Can you add support for use of variable in request body(payload)?

**Comment by vjay21** [comment]
any update on this? this request is still needed for me.
to give context:

@URL = {{$URL}}
@USER = user1
###
POST {{URL}}/api/v2/test/getuser
{
"user": {{USER}} <<----- which wont as of today
}

**Comment by lima1909** [comment]
I think I've implemented it. You can see an example here:
https://github.com/lima1909/resty.nvim/blob/6593c19f2ff93057562e41a9ee1b22503b7e5e91/example/example.http#L51

@vjay21 
Please let me know if it works.

**Comment by vjay21** [comment]
Still not working for me.

<img width="829" height="285" alt="Image" src="https://github.com/user-attachments/assets/b384d71f-4575-4523-81c6-5ffd45beb86f" />

<img width="708" height="624" alt="Image" src="https://github.com/user-attachments/assets/a30085f3-5a64-4933-8ea8-6dfa961e174c" />

**Comment by lima1909** [comment]
I think, the issue is, that your `{{CLIENT_ID}}` is not a string: `"{{CLIENT_ID}}"` (quotation marks), therefore, your body is not a valid JSON.
I have added more information, if an error occurred. Maybe, that helps.

**Comment by vjay21** [comment]
Thanks @lima1909 for suggestion, i could post now. Thanks again, you saved a lot of efforts updating and firing REST calls.
